language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=2.6.1

before_install:
  # login docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  # build image
  - docker-compose -f docker-compose-build.yaml build --parallel
  # tag image
  - docker tag udagram-api-feed hungnhi92/udagram-api-feed:v1
  - docker tag udagram-api-user hungnhi92/udagram-api-user:v1
  - docker tag udagram-frontend hungnhi92/udagram-frontend:v1
  - docker tag udagram-reverseproxy hungnhi92/udagram-reverseproxy:v1
  # push image
  - docker push hungnhi92/udagram-api-feed:v1
  - docker push hungnhi92/hungnhi92/udagram-api-user:v1
  - docker push hungnhi92/udagram-frontend:v1
  - docker push hungnhi92/udagram-reverseproxy:v1
  